# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: buildConfig
    displayName: Buildl Configuration to Use
    default: Debug
    values:
      - Debug
      - Release
      
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
 buildConfiguration: ${{ parameters.buildConfig }}

steps:
- task: UseDotNet@2
  displayName: Setup .NET SDK Version 3.x
  inputs:
    packageType: sdk
    version: 5.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build the Assembly'
  inputs:
    command: build
    versioningScheme: byBuildNumber
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Package up the Assembly
  inputs:
   command: 'pack'
   packagesToPack: './CustardApi/*.csproj'
   nobuild: true
   verbosityPack: 'Normal'
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '9be038d0-6fcd-4e79-b1a5-1d45141d58a5/b940ac25-48de-4f50-ad6a-851d55932486'
